"""add human_tickets table

Revision ID: a8e85d881b28
Revises: e01f31c574ab
Create Date: 2026-08-26 09:57:27.392153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# JSONB variant 引用的 Text 需要显式导入
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'a8e85d881b28'
down_revision: Union[str, Sequence[str], None] = 'e01f31c574ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_tickets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('intervention_reason', sa.Text(), nullable=True),
    sa.Column('compliance_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_tickets_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_tickets_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_human_tickets_conversation_id'))

    op.drop_table('human_tickets')
    # ### end Alembic commands ###
